"""initial schema

Revision ID: 9a536b7c0328
Revises: 
Create Date: 2026-06-03 15:30:03.750791

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a536b7c0328'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_active_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_connections_type'), ['type'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('html', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queries', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_name'), ['name'], unique=True)

    op.create_table('predefined_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cell_view', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'query_name', name='uq_predefined_type_name')
    )
    with op.batch_alter_table('predefined_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predefined_queries_query_name'), ['query_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_predefined_queries_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predefined_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predefined_queries_type'))
        batch_op.drop_index(batch_op.f('ix_predefined_queries_query_name'))

    op.drop_table('predefined_queries')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_name'))

    op.drop_table('dashboards')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_type'))
        batch_op.drop_index(batch_op.f('ix_connections_name'))

    op.drop_table('connections')
    # ### end Alembic commands ###
